---
title: "Be a good citizen"
---

Niwot is indebted to its funder (the [National Science Foundation](https://www.nsf.gov/)), the [people](https://nwt.lternet.edu/our-team) who collect the data and the [historical occupants of Niwot Ridge](https://www.colorado.edu/about/land-acknowledgment).

## Citing Data

If you use a Niwot dataset in your research, remember to cite it, so that we can track data useage for ourselves, and for our funders. The landing page on each dataset provides a suggested citation format. If a journal requests a different format, that's fine too so long as the citation includes the DOI. And yes - you should cite a dataset – even if it is one you provided.

## Acknowledge Niwot funding

The following acknowledgment should accompany any publication that makes use of Niwot resources: Logistical support and/or data were provided by the NSF-supported Niwot Ridge LTER program (NWT VII: NSF DEB – 1637686, NWT VIII: NSF DEB-2224439)

## Add a land acknowledgement

Suggested text can be found on the [Niwot Ridge](https://nwt.lternet.edu/guidelines-for-researchers) and/or [University of Colorado](https://www.colorado.edu/about/land-acknowledgment) websites

## Consider Co-authorship

All Niwot data are provided free of charge, for use without restriction. However if your analysis relies heavily on data collected by others, consider asking them to collaborate. Niwot LTER's recommended authorship guidelines can be found [here](https://static1.squarespace.com/static/5c4f6792ec4eb7c7c4186cc0/t/60707d88b8fd40612c9b2501/1617984904972/NWT+LTER+Authorship+Guideline+Spring+2021.pdf).

## Acknowledge Niwot Researchers, technicians and seasonals

We encourage data re-use. If co-authorship is not appropriate, consider adding an acknowledgement to your manuscript instead. The 'people' element of the metadata file is a good place to start.

## Keep up to date with the latest recommendations

Our [website](https://nwt.lternet.edu/guidelines-for-researchers) has the most up to date information on authorship and citations.
